constant:
  in_year: 1995
  out_year: 2018
  delay_length: [30, 40, 50, 60]
  EPOCH: 200
  omni_param: [
    "B_Total",
    "BZ_GSE",
    "flow_speed",
    "Vx",
    "T",
    "Pressure",
    "E_Field",
    "proton_density",
  ]
  auroral_param: [
    "AE_INDEX",
    "AU_INDEX",
    "AL_INDEX"
  ]


data:
  auroral_index: 'AE_INDEX'
  set_split: "organized"
  scaler_type: "robust"

  test_size: 0.15


cv:
  n_split: 5
  gap: 0
  max_train_size: null


nn:
  #* Hyperparameters
  type_model: "TCNN_LSTM"
  batch_test: 1040
  lr: 0.00005
  patience: 100
  drop: 0.25
  optimizer_type: "Adam"
  schler: "Reduce"
  patience_schler: 10

  #* LSTM
  num_layer_lstm: 7
  hidden_neurons_lstm: 128

  #*GRU
  num_layer_gru: 2
  hidden_neurons_gru: 128

  #* CNN & TCNN
  kernel_size: 9

  #*TCNN
  num_chanel_list_tcnn: [128, 128, 256, 64]


  #* TRANSFORMER
  d_model_transformer: 64
  nhead_transformer: 4
  num_encoder_layers_transformer: 3
  dim_feedforward_transformer: 128

